import React from "react"
import Button from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/20NAw98U29at3n327QbUXS/Claris-Design-System---Web?node-id=30%3A609",
  {
    props: {
      leftIcon: figma.instance("left icon"),
      buttonText: figma.string("Button text"),
      label: figma.enum("Label", {
        Text: "text",
        "Symbol+text": "symbol-text",
        Symbol: "symbol",
      }),
      type: figma.enum("Type", {
        Primary: "primary",
        Secondary: "secondary",
        Tertairy: "tertairy",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Pressed: "pressed",
        Focused: "focused",
        Disabled: "disabled",
      }),
      size: figma.enum("Size", {
        Large: "large",
        Medium: "medium",
        Small: "small",
      }),
    },
    example: (props) => <Button />,
  },
)
