import React from "react"
import { Input } from "./Input"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Input,
  "https://www.figma.com/design/20NAw98U29at3n327QbUXS/Claris-Design-System---Web?node-id=1362%3A305",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      variant: figma.enum("Variant", {
        Regular: "regular",
        Search: "search",
        Password: "password",
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      state: figma.enum("State", {
        Disabled: "disabled",
        Default: "default",
        Hover: "hover",
        Focused: "focused",
        "Read-Only": "read-only",
      }),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      readOnly: figma.enum("State", {
        "Read-Only": true,
      }),
    },
    example: (props) => (
      <Input
        variant={props.variant}
        size={props.size}
        state={props.state}
        disabled={props.disabled}
        readOnly={props.readOnly}
      />
    ),
  },
)
